apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: helloworld
    version: v2
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
        - image: kelseyhightower/helloworld:v2 
          name: helloworld
          ports:
            - containerPort: 8080
              name: http
